name: Java8

on: [push]

jobs:
  java8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14, windows-2016]
        update: [x, 222, 212, 202, 201, 192, 181, 172, 163, 162, 152, 144, 131, 121, 112, 102, 101, 92, 91, 72, 71]
        exclude:
          # excludes node 4 on macOS
          - os: macos-10.14
            update: [121, 112, 102, 101, 92, 91, 72, 71]
          - os: ubuntu-18.04
            update: [101]
      fail-fast: false
      max-parallel: 5
    name: JDK 8.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8.0.${{ matrix.update }}
    - name: java -version
      run: java -version
