name: Java14

on:
  push:
    paths:
      - '*/*/java14.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */3 * * *'
      
jobs:
  java13:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2016]
        update: [14.0.0-ea, 14.0.0-ea.28, 14.0.0-ea.27, 14-ea]
      fail-fast: false
      max-parallel: 5
    name: JDK ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: giltene/setup-java@master
      with:
        java-version: ${{ matrix.update }}
    - name: java -version
      run: java -version
