name: Java7

on:
  push:
    paths:
      - '*/*/java7.yml'

jobs:
  java8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14, windows-2016]
        update: [x, 232, 222, 211, 201, 191, 181, 171, 161, 162, 154, 141, 131, 121, 111, 101, 95]
      fail-fast: false
      max-parallel: 5
    name: JDK 7.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 7.0.${{ matrix.update }}
    - name: java -version
      run: java -version
