name: Java12

on:
  push:
    paths:
      - '*/*/java12.yml'

jobs:
  java8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14, windows-2016]
        update: [x, 2, 1, 0, 0-ea]
      fail-fast: false
      max-parallel: 5
    name: JDK 12.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 12.0.${{ matrix.update }}
    - name: java -version
      run: java -version
