name: probe

on:
  push:
    paths:
      - '.github/workflows/probe.yml'

jobs:
  java8fx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest]
        update: [8.0.x, 11.0.x, 11.0.9.1]
      fail-fast: false
      max-parallel: 5
    name: JDK ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: java -version
      run: java -version
    - name: usr/lib/jvm
      run: ls /usr/lib/jvm
